### ISSUE TITLE
No Support for GPS/GNSS data ?

### ISSUE THREAD

**Issue by salmanfarisvp** [SeeedJP/WioLTEforArduino#24] opened 2019-04-16 19:32 UTC
Is there any example sketch to access the GPS/GNSS data?

**Comment by salmanfarisvp** [comment] 2019-04-17 06:14
https://github.com/Seeed-Studio/Wio_LTE_Arduino_Library this one supported GNSS but it doesn't have the Soracomm example.

**Comment by ytsuboi** [comment] 2019-04-17 07:24
Hi @salmanfarisvp 
We are not providing GNSS support on this library because somehow the cellular module used on Wio LTE JP version doesn't have that function. So actually this is the first time to hear the GNSS support request. Which version of Wio LTE are you trying to use in where?

**Comment by salmanfarisvp** [comment] 2019-04-17 18:52
Hi @ytsuboi 
As a part of the Hackster Soracom contest (https://www.hackster.io/contests/soracomcontest), I received the WIO LTE v1.3b Europe Kit, and for my application, I need both GSM and GNSS, but the lib provided with the doc can't find any information about GPS, but my module is capable of GPS.
Is there any way to get the GPS coordinate data

**Comment by bluetiger9** [comment] 2019-04-27 17:58
@salmanfarisvp, I did a try and got the GNSS example from [Seeed-Studio/Wio_LTE_Arduino_Library](https://github.com/Seeed-Studio/Wio_LTE_Arduino_Library) working on the EU board.

I will try to port the GNSS functionality to this library. I will let you know when is done.

The GNSS functionality is implemented in this class:
https://github.com/Seeed-Studio/Wio_LTE_Arduino_Library/blob/master/gnss.cpp

@ytsuboi, when done I think we can integrate the GNSS library here. So, at least non-JP users would be able to use it. It's strange why Quectel choose to not support GNSS for the EC21-J.

Thanks,
Attila

**Comment by salmanfarisvp** [comment] 2019-04-28 06:18
@bluetiger9 Thank you, I will also trying to implement  .

**Comment by bluetiger9** [comment] 2019-04-28 09:23
Added basic GNSS functionality to the library. Getting coordinates (lat + long), altitude and UTC time are supported.

For anyone interested, the changes are located in the [bluetiger9/WioLTEforArduino](https://github.com/bluetiger9/WioLTEforArduino) repository. They can be merged _(copied)_ into the `<HOME>/Arduino/libraries/Wio_LTE_for_Arduino` folder.

Also added an example: `Wio LTE for Arduino -> gnss -> GetGNSSLocation`. This should be visible after the Arduino IDE is restarted.

**Comment by salmanfarisvp** [comment] 2019-05-05 16:18
Thank @bluetiger9  it's working.

**Comment by salmanfarisvp** [comment] 2019-05-18 10:41
@bluetiger9 , now it showing some error, can you please take a look .

```
## I/O Initialize.
### Power supply ON.
### Power supply GNSS.
### Turn on or reset.
### Enable GNSS.
### ERROR! ###
### Get GNSS location.
### ERROR! ###
### Get GNSS location.
### ERROR! ###
```

**Comment by salmanfarisvp** [comment] 2019-05-18 17:02
@bluetiger9 @ytsuboi  Please take a look https://github.com/SeeedJP/WioLTEforArduino/pull/27

**Comment by matsujirushi** [comment] 2019-05-19 10:29
@salmanfarisvp 

Can you enable WIO_DEBUG macro and get log at SeeedJP:master branch ?

https://github.com/SeeedJP/WioLTEforArduino/blob/master/src/WioLTEConfig.h#L17

**Comment by bluetiger9** [comment] 2019-05-19 12:41
Hi @matsujirushi,

I can confirm that the GNSS does not always works without the retry mechanism.

> @salmanfarisvp
> 
> Can you enable WIO_DEBUG macro and get log at SeeedJP:master branch ?
> 
> https://github.com/SeeedJP/WioLTEforArduino/blob/master/src/WioLTEConfig.h#L17

Here are the debug logs:
- without retry:
```
### Enable GNSS.
<- AT+QGPS=1
-> 
-> ERROR
-> 
-> +CFUN: 1
-> 
-> +QIND: SMS DONE
-> 
-> +QIND: PB DONE
### TIMEOUT ###
ERROR! 1207
### ERROR! ###
```
- with retry:
```
### Enable GNSS.
<- AT+QGPS?
-> 
-> +QGPS: 0
-> 
-> OK
-> 
-> +CFUN: 1
-> 
-> +QIND: SMS DONE
-> 
-> +QIND: PB DONE
### TIMEOUT ###
<- AT+QGPS=1
-> 
-> OK
<- AT+QGPS?
-> 
-> +QGPSURC: "xtradataexpire",0,"1980/01/05,19:00:00"
-> 
-> +QGPS: 1
```

Cheers,
Attila

**Comment by matsujirushi** [comment] 2019-05-20 00:48
Hi all,
I modified EnableGNSS().

@bluetiger9 @salmanfarisvp 
Please test SeeedJP:dev-gnss code.
Thanks.

**Closed** 2019-07-11 10:16 UTC
Labels: enhancement
